name: Functions deploy via serverless - Dev
on:
  push:
    branches:
      - "main"

jobs:
  functions-build-and-upload:
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Display the path
      run: echo $PATH
      shell: bash
      
    - uses: Teakowa/setup-serverless@v2.0.0
      with:
        provider: azure
      env:
        AZURE_SUBSCRIPTION_ID: "bd709d65-0b57-415c-a331-597434af1ea7"
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AIR_APPKEY: ${{ secrets.AIR_APPKEY }}
        AIR_APIKEY: ${{ secrets.AIR_APIKEY }}
    - run: cd collector && sls deploy --stage dev
