name: Functions deploy via serverless - Dev
on:
  push:
    branches:
      - "main"

jobs:
  functions-build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Install Dependencies
        uses: rstuven/npm-install@auth-token-v2.1
        with:
          working-directory: ./collector

      - name: Deploy Functions
        env:
          AZURE_SUBSCRIPTION_ID: "bd709d65-0b57-415c-a331-597434af1ea7"
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AIR_APPKEY: ${{ secrets.AIR_APPKEY }}
          AIR_APIKEY: ${{ secrets.AIR_APIKEY }}
        
        run: cd collector && npx sls deploy --stage dev