name: Functions deploy via serverless - Dev
on:
  push:
    branches:
      - "main"

jobs:
  functions-build-and-upload:
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Display the path
      run: echo $PWD

    - name: Install packages
      run: cd collector && npm install

    - name: Deploy to azure
      env:
        AZURE_SUBSCRIPTION_ID: "bd709d65-0b57-415c-a331-597434af1ea7"
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AIR_APPKEY: ${{ secrets.AIR_APPKEY }}
        AIR_APIKEY: ${{ secrets.AIR_APIKEY }}
      run: npx sls deploy --stage dev
